/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kfzvjlrhlaxpcpiwibis"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmenZqbHJobGF4cGNwaXdpYmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNjY4ODQsImV4cCI6MjA3OTk0Mjg4NH0.k7kR_pH1r6BfeTJh7hNHqIODFuFA-4LQBrThw-jQHlc"